name: pandoc-test

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with:
          args: -s ./input/simple.md -o simple.pdf  -V documentclass=ltjsarticle --pdf-engine=lualatex
      - name: output files
        uses: actions/upload-artifact@v1
        with:
          name: pandoced-files
          path: simple.pdf