name: pandoc-test

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with:
          args: -s ./input/sample.md -o sample.html
      - name: output files
        uses: actions/upload-artifact@v1
        with:
          name: pandoced-files
          path: sample.html